### ISSUE TITLE
Is thereinterest on making this add-on Plone 4.2 compatible?

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.revisionmanager#12]
I need to use this package on a site running Plone 4.2; in order to make it work I will need to make some changes like bringing back the `Extensions/Install.py` and change some pinnings.

Is that something you can live with?

**Comment by hvelarde** [comment]
@mauritsvanrees BTW, Plone 2 uses `Products.CMFQuickInstallerTool = 3.0.6` and Plone 4.3 uses `Products.CMFQuickInstallerTool = 3.0.13` which should be a bug fix release.

it seems at some point we lost compatibility with Plone 4.2, so we should had released using a different numbering.

I haven't researched in depth, that's just what I found quickly.

thanks!

**Comment by mauritsvanrees** [comment]
Do you mean CMFQuickInstallerTool 3.0.13 does not work at all on Plone 4.2?
In the changelog I see only bug fixes and minor additions, nothing that strikes me as backwards incompatible. But individual add-ons might need changes if they rely on previously buggy behavior.

**Comment by hvelarde** [comment]
I need to test it more in depth, but some requirements were failing.

**Comment by tschorr** [comment]
I have no problem with that as long as support for newer Plone versions isn't affected. Feel free to send a PR.

**Comment by hvelarde** [comment]
I thin the problem is in fact related with the way the configlets were created; I'll do some research next week.

In the future we can drop compatibility but we need to have at least one working version for older sites.

BTW, thank you very much for this add-on! it's making me having a better life ;-)

**Comment by tschorr** [comment]
You're welcome :-)
What about having a separate branch for 4.2?
