### ISSUE TITLE
Clean up orphaned revisions doesn't work on Plone 5.1.5

### ISSUE THREAD

**Issue by fredvd** [collective/collective.revisionmanager#19]
When I installed collective.revisionmanager 0.8 in a Plone 5.1.5 site
* calculate statistics,
* and try to delete all revisions for already deleted content items
* recalculate staticts

nothing happens. The statistics still show the same number of revisions belonging to deleted items. 

Doing exactly the same in a Plone 4.3.18 website set all revisions belonging to deleted items to 0. 

This is a Plone 5.1 site, I would expect problems with Plone 5.2 with a completely updated Zope 4 stack, but 5.1 and 4.3.18 still use the same Zope somewhat.

**Comment by mauritsvanrees** [comment]
Confirmed. The test buildout of this package uses Plone 5.0, where it works. When I update this to 5.1, deleting orphans no longer works.
When I go to the control panel, and then the _List histories_ tab, I see in lines where it has gone wrong: "All revisions have been purged". But the history is apparently still there:

![Screenshot 2019-10-02 at 21 35 02](https://user-images.githubusercontent.com/210587/66076018-24956300-e55d-11e9-83f4-25329d6dac43.png)

Restarting Zope does not help. Using the _Recalculate statistics_ button does not help. The [ZMI](http://localhost:8080/Plone/portal_historiesstorage/storageStatistics) shows the same.

**Comment by mauritsvanrees** [comment]
I see the problem. Plone 5.1 uses CMFEditions 3.x, and this automatically [purges versions of content that is deleted](https://github.com/plone/Products.CMFEditions/pull/44).

So in Plone 5.1:
- When you delete an item, the history gets purged. The only thing that remains, is a bit of metadata.
- Deleting the orphans does nothing.
- Well, when you have deleting a Document in Plone 5.0, then upgraded to 5.1, and then delete the orphans, then this will completely get purged, as wanted.

So what is missing, is removing the small remaining metadata.

I will prepare a PR.
(I took the liberty of merging two of my own PRs from yesterday, so Travis is passing again.)

**Comment by tschorr** [comment]
@fredvd collective.revisionmanager 0.9 is out, could you check and verify whether it fixes your issue?

**Comment by mauritsvanrees** [comment]
I think this can be closed.
