### ISSUE TITLE
New release 0.9?

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/collective.revisionmanager#24]
@tschorr Can you look at merging my small PRs #22 and #23 and make a new release 0.9?

And can you grant the 'collective' user PyPI rights?

There is also the WIP PR #18 from @pbauer which adds Python 3 support, but it may be safer to do that in a 1.0 release, as there can always be a corner case that then no longer works, or Travis gets harder. Maybe make that for Plone 5.0+ only.

**Comment by tschorr** [comment]
@mauritsvanrees thanks for your PRs, I have merge #22 but have a question on #23, pls see there. I'm happy to release v 0.9 when we resolve this. Also 'collective' is now package owner on PyPI.

**Comment by tschorr** [comment]
collective.revisionmanager 0.9 released + uploaded to PyPI.

**Comment by mauritsvanrees** [comment]
Thanks!
